### PR TITLE
Dahn add tests

### PR DESCRIPTION
**Pull request by Dahnepfl**
Added :
 - Browser URL
- Utility test class and refactoring
- Test about the intent of the mainactivity

- Test about mainactivity

- Tests about the menu : now check if the fragment is open

- Rearange code

- Way more :smiling_imp: :

### CODE REVIEW

**Comment by Dahnepfl** [comment]
Because of the code added / modified, Codeclimate complain about my test coverage... But we have more tests !

**Comment by Dahnepfl** [comment]
@Globoxx 

I tried to implement a chat test.... Not as you suggested. Maybe I do it the wrong way ? You can have a look on my last commit

**Comment by Globoxx** [comment]
> @Globoxx
> 
> I tried to implement a chat test.... Not as you suggested. Maybe I do it the wrong way ? You can have a look on my last commit

@Dahnepfl 
But you click on the send button so you add a message to the database. It seems weird to have to actually send messages to the database to test the behavior of the fragment.

**Comment by Dahnepfl** [comment]
> > @Globoxx
> > I tried to implement a chat test.... Not as you suggested. Maybe I do it the wrong way ? You can have a look on my last commit
> 
> @Dahnepfl
> But you click on the send button so you add a message to the database. It seems weird to have to actually send messages to the database to test the behavior of the fragment.

That's right

But maybe the test are just made to be used in a test environement, with a database test environement ? 

Or we need to use mock, I don't know.

**Pull request merged**
